
backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "merken"
    label: "Merken"
    folder: "merken"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
      - {label: "Introductie", name: "intro", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image"}
      - {label: "SEO tekst", name: "body", widget: "markdown"}
  - name: "producten"
    label: "Producten"
    folder: "producten"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
      - {label: "Omschrijving", name: "omschrijving", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image"}
      - {label: "Prijs vanaf", name: "prijs", widget: "string"}
      - {label: "Merk", name: "merk", widget: "string"}
      - {label: "Inhoud", name: "body", widget: "markdown"}
  - name: "blogs"
    label: "Blogs"
    folder: "blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Afbeelding", name: "image", widget: "image"}
      - {label: "Inhoud", name: "body", widget: "markdown"}
